Train:
  epochs: 100000
  batch_size: 5
  train_num_batches: 100
  save_rate: 50
  plot_rate: 4
  learning_rate: 0.00001
  lr_step_size: 30
  lr_gamma: 0.5
  reconstruction_loss_weight: -1
  latent_loss_weight: 1
  kl_div_loss_weight: 1

network:
  model: Encoder
  ResNetVersion: resnet18

loss:
  loss_type: MSE
