Train:
  epochs: 100
  batch_size: 64
  train_num_batches: 50
  val_num_batches: 20
  save_rate: 10
  plot_rate: 4
  learning_rate: 0.00001
  lr_step_size: 30
  lr_gamma: 0.5
  reconstruction_loss_weight: 1
  latent_loss_weight: 1

network:
  model: Encoder

loss:
  loss_type: MSE
