Train:
  epochs: 100000
  batch_size: 8
  train_num_batches: 100
  save_rate: 50
  plot_rate: 4
  learning_rate: 0.000001
  lr_step_size: 30
  lr_gamma: 0.5
  reconstruction_loss_weight: 3
  latent_loss_weight: 1

network:
  model: ResNet
  ResNetVersion: resnet18

loss:
  loss_type: MSE
